### ISSUE TITLE
How to include this in an existing plugin?

### ISSUE THREAD

**Issue by pgroot91** [nsrosenqvist/cmb2-switch#1]
How to include this in an existing plugin?

require_once( 'includes/cmb2-switch/cmb2-switch.php' );

Getting the default error:
Fatal error: Call to undefined function cmb2_set_switch_default()

**Comment by nsrosenqvist** [comment]
You need to include the helpers file first since that is where cmb2_set_switch_default is defined. I noticed that it's included in the wrong order in the plugin file (I've never used it myself, only install via composer) so I fixed it in master. So if you pull down master it should hopefully work, or just include it yourself prior to including the other files.
